In [1]:
import pandas as pd
import numpy as np
from datasets import Dataset, load_dataset
from huggingface_hub import HfApi
from tqdm.std import tqdm
import json

In [2]:
input_task_0015 = "output_files/selected_output/selected_mathematical_reasoning_0015.xlsx"
input_task_0117 = "output_files/selected_output/selected_mathematical_reasoning_0117.xlsx"
input_task_0126 = "output_files/selected_output/selected_mathematical_reasoning_0126.xlsx"

In [3]:
df_0015 = pd.read_excel(input_task_0015)
df_0117 = pd.read_excel(input_task_0117)
df_0126 = pd.read_excel(input_task_0126)

df_0015 = df_0015.sample(frac=0.5)
df_0117 = df_0117.sample(frac=0.5)
df_0126 = df_0126.sample(frac=0.5)

In [4]:
df_0015

,assertion.code,assertion.detail,assertion.run-date,assertion.severity,assertion.source,assertion.type,entity.cik,entity.name,report.accepted-timestamp,report.accession,...,calculation,definition,label,instance,us_gaap,input,true_answer,segmentation_path,parse_successful,LLM_Output
51,DQC.US.0015.6891,"2023-01-26 09:00:53,997 [DQC.US.0015.6891] us-...",2023-01-26,ERROR,DQC,15,1133421,NORTHROP GRUMMAN CORP /DE/,2023-01-26 08:32:00,0001133421-23-000006,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:DefinedBenefitPlan...,{'tag': 'us-gaap:DefinedBenefitPlanBenefitObli...,"{'extracted_value': '-1,964,000,000', 'calcula...",10k-noc-20221231/RetirementBenefitsFundedStatu...,True,{'error_tags': {'tag': 'us-gaap:DefinedBenefit...
15,DQC.US.0015.7095,"2022-11-13 14:33:56,968 [DQC.US.0015.7095] us-...",2022-11-13,ERROR,DQC,15,1501756,"Adverum Biotechnologies, Inc.",2022-11-10 16:18:00,0001628280-22-029499,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:SubleaseIncome\nLa...,"{'tag': 'us-gaap:SubleaseIncome', 'period': '2...","{'extracted_value': '-4,100,000', 'calculated_...",10q-advm-20220930/LeasesAdditionalInformationD...,True,{'error_tags': {'tag': 'us-gaap:SubleaseIncome...
28,DQC.US.0015.6070,"2023-01-06 10:30:33,684 [DQC.US.0015.6070] us-...",2023-01-06,ERROR,DQC,15,1170010,"CARMAX, INC.",2023-01-06 09:58:00,0001170010-23-000006,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:OtherReceivables\n...,"{'tag': 'us-gaap:OtherReceivables', 'period': ...","{'extracted_value': '-4,200,000', 'calculated_...",10q-kmx-20221130/AutoLoanReceivablesAutoLoanRe...,True,{'error_tags': {'tag': 'us-gaap:OtherReceivabl...
10,DQC.US.0015.7635,"2022-12-29 16:45:43,439 [DQC.US.0015.7635] srt...",2022-12-29,ERROR,DQC,15,10048,"BARNWELL INDUSTRIES, INC.",2022-12-29 16:12:00,0000010048-22-000029,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: srt:StandardizedMeasureOfD...,{'tag': 'srt:StandardizedMeasureOfDiscountedFu...,"{'extracted_value': '-176,000', 'calculated_va...",10k-brn-20220930/SUPPLEMENTARYOILANDNATURALGAS...,True,{'error_tags': {'tag': 'srt:StandardizedMeasur...
46,DQC.US.0015.5879,"2023-01-26 09:00:53,998 [DQC.US.0015.5879] us-...",2023-01-26,ERROR,DQC,15,1133421,NORTHROP GRUMMAN CORP /DE/,2023-01-26 08:32:00,0001133421-23-000006,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:DefinedBenefitPlan...,{'tag': 'us-gaap:DefinedBenefitPlanAssumptions...,"{'extracted_value': '-0.0258', 'calculated_val...",10k-noc-20221231/RetirementBenefitsPlanAssumpt...,True,{'error_tags': {'tag': 'us-gaap:DefinedBenefit...
56,DQC.US.0015.6897,"2023-01-26 09:00:53,999 [DQC.US.0015.6897] us-...",2023-01-26,ERROR,DQC,15,1133421,NORTHROP GRUMMAN CORP /DE/,2023-01-26 08:32:00,0001133421-23-000006,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:DefinedBenefitPlan...,{'tag': 'us-gaap:DefinedBenefitPlanPlanAssetsB...,"{'extracted_value': '-1,973,000,000', 'calcula...",10k-noc-20221231/RetirementBenefitsFundedStatu...,True,{'error_tags': {'tag': 'us-gaap:DefinedBenefit...
59,DQC.US.0015.9103,"2023-02-09 17:35:44,293 [DQC.US.0015.9103] us-...",2023-02-09,ERROR,DQC,15,1504461,NGL Energy Partners LP,2023-02-09 16:49:00,0001504461-23-000010,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:DerivativeNonmonet...,{'tag': 'us-gaap:DerivativeNonmonetaryNotional...,"{'extracted_value': '-12,000', 'calculated_val...",10q-ngl-20221231/FairValueofFinancialInstrumen...,True,{'error_tags': {'tag': 'us-gaap:DerivativeNonm...
21,DQC.US.0015.2419,"2023-01-06 10:30:33,685 [DQC.US.0015.2419] us-...",2023-01-06,ERROR,DQC,15,1170010,"CARMAX, INC.",2023-01-06 09:58:00,0001170010-23-000006,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:ShareBasedCompensa...,{'tag': 'us-gaap:ShareBasedCompensationArrange...,"{'extracted_value': '-80,000', 'calculated_val...",10q-kmx-20221130/StockandStockBasedIncentivePl...,True,{'error_tags': {'tag': 'us-gaap:ShareBasedComp...
27,DQC.US.0015.427,"2023-01-06 10:30:33,685 [DQC.US.0015.427] us-g...",2023-01-06,ERROR,DQC,15,1170010,"CARMAX, INC.",2023-01-06 09:58:00,0001170010-23-000006,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:CapitalExpenditure...,{'tag': 'us-gaap:CapitalExpendituresIncurredBu...,"{'extracted_value': '-9,933,000', 'calculated_...",10q-kmx-20221130/SupplementalCashFlowInformati...,True,{'error_tags': {'tag': 'us-gaap:CapitalExpendi...
107,DQC.US.0015.2973,"2024-11-01 18:35:19,522 [DQC.US.0015.2973] us-...",2024-11-01,ERROR,DQC,15,39263,"Cullen/Frost Bankers, Inc.",2024-10-31 15:06:00,0000039263-24-000069,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:RestrictedStockExp...,"{'tag': 'us-gaap:RestrictedStockExpense', 'per...","{'extracted_value': '-521,000', 'calculated_va...",10q-cfr-20240930/StockBasedCompensationStockBa...,True,{'error_tags': {'tag': 'us-gaap:RestrictedStoc...
95,DQC.US.0015.7193,"2024-11-18 06:10:55,262 [DQC.US.0015.7193] us-...",2024-11-18,ERROR,DQC,15,1527702,iQSTEL Inc.,2024-11-14 08:06:00,0001663577-24-000281,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:DebtInstrumentUnam...,{'tag': 'us-gaap:DebtInstrumentUnamortizedDisc...,"{'extracted_value': '-490,022', 'calculated_va...",10q-iqst-20240930/BalanceSheetsParenthetical,True,{'error_tags': {'tag': 'us-gaap:DebtInstrument...
66,DQC.US.0015.2894,"2023-11-02 22:03:09,705 [DQC.US.0015.2894] us-...",2023-11-03,ERROR,DQC,15,1423902,"WESTERN MIDSTREAM PARTNERS, LP",2023-11-01 16:21:00,0001423902-23-000065,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:ProceedsFromSaleOf...,{'tag': 'us-gaap:ProceedsFromSaleOfProductiveA...,"{'extracted_value': '-60000', 'calculated_valu...",10q-wes-20230930/ConsolidatedStatementsofCashF...,True,{'error_tags': {'tag': 'us-gaap:ProceedsFromSa...
90,DQC.US.0015.1302,"2024-11-18 06:10:55,261 [DQC.US.0015.1302] us-...",2024-11-18,ERROR,DQC,15,1527702,iQSTEL Inc.,2024-11-14 08:06:00,0001663577-24-000281,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:IncomeTaxesPaid\nL...,"{'tag': 'us-gaap:IncomeTaxesPaid', 'period': '...","{'extracted_value': '-134,880', 'calculated_va...",10q-iqst-20240930/ConsoolidatedStatementsOfCas...,True,{'error_tags': {'tag': 'us-gaap:IncomeTaxesPai...
62,DQC.US.0015.2894,"2023-02-10 07:31:07,100 [DQC.US.0015.2894] us-...",2023-02-10,ERROR,DQC,15,1564708,NEWS CORPORATION,2023-02-10 07:05:00,0001564708-23-000012,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:ProceedsFromSaleOf...,{'tag': 'us-gaap:ProceedsFromSaleOfProductiveA...,"{'extracted_value': '-2000000', 'calculated_va...",10q-nws-20221231/ConsolidatedStatementsofCashF...,True,{'error_tags': {'tag': 'us-gaap:ProceedsFromSa...
30,DQC.US.0015.2416,"2023-01-26 09:00:53,992 [DQC.US.0015.2416] us-...",2023-01-26,ERROR,DQC,15,1133421,NORTHROP GRUMMAN CORP /DE/,2023-01-26 08:32:00,0001133421-23-000006,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:ShareBasedCompensa...,{'tag': 'us-gaap:ShareBasedCompensationArrange...,"{'extracted_value': '-64,000', 'calculated_val...",10k-noc-20221231/StockCompensationPlansStockAw...,True,{'error_tags': {'tag': 'us-gaap:ShareBasedComp...
98,DQC.US.0015.7210,"2024-11-18 06:10:55,264 [DQC.US.0015.7210] us-...",2024-11-18,ERROR,DQC,15,1527702,iQSTEL Inc.,2024-11-14 08:06:00,0001663577-24-000281,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:DividendsPreferred...,"{'tag': 'us-gaap:DividendsPreferredStock', 'pe...","{'extracted_value': '-816,480', 'calculated_va...",10q-iqst-20240930/StatementsOfOperations,True,{'error_tags': {'tag': 'us-gaap:DividendsPrefe...
39,DQC.US.0015.4007,"2023-01-26 09:00:53,996 [DQC.US.0015.4007] us-...",2023-01-26,ERROR,DQC,15,1133421,NORTHROP GRUMMAN CORP /DE/,2023-01-26 08:32:00,0001133421-23-000006,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:DefinedBenefitPlan...,{'tag': 'us-gaap:DefinedBenefitPlanAssumptions...,"{'extracted_value': '-0.0293', 'calculated_val...",10k-noc-20221231/RetirementBenefitsPlanAssumpt...,True,{'error_tags': {'tag': 'us-gaap:DefinedBenefit...
73,DQC.US.0015.2688,"2024-02-13 13:33:08,026 [DQC.US.0015.2688] us-...",2024-02-13,ERROR,DQC,15,1657853,"HERTZ GLOBAL HOLDINGS, INC.",2024-02-12 17:11:00,0001657853-24-000022,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:Assets\nLabel: Ass...,"{'tag': 'us-gaap:Assets', 'period': '2023-12-31'}","{'extracted_value': '-1,000,000', 'calculated_...",10k-htz-20231231/DivestituresDetails,True,"{'error_tags': {'tag': 'us-gaap:Assets', 'peri..."
72,DQC.US.0015.2688,"2024-02-13 13:33:08,026 [DQC.US.0015.2688] us-...",2024-02-13,ERROR,DQC,15,1657853,"HERTZ GLOBAL HOLDINGS, INC.",2024-02-12 17:11:00,0001657853-24-000022,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:Assets\nLabel: Ass...,"{'tag': 'us-gaap:Assets', 'period': '2022-12-31'}","{'extracted_value': '-1000000', 'calculated_va...",10k-htz-20231231/DivestituresDetails,True,"{'error_tags': {'tag': 'us-gaap:Assets', 'peri..."
82,DQC.US.0015.2894,"2024-08-02 16:12:51,529 [DQC.US.0015.2894] us-...",2024-08-02,ERROR,DQC,15,1653653,"RED ROCK RESORTS, INC.",2024-02-21 14:28:00,0001653653-24-000004,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:ProceedsFromSaleOf...,{'tag': 'us-gaap:ProceedsFromSaleOfProductiveA...,"{'extracted_value': '-76,300,000', 'calculated...",10k-rrr-20231231/WritedownsandOtherNetDetails,True,{'error_tags': {'tag': 'us-gaap:ProceedsFromSa...
108,DQC.US.0015.2419,"2024-08-26 17:21:53,045 [DQC.US.0015.2419] us-...",2024-08-26,ERROR,DQC,15,1514056,TITAN ENVIRONMENTAL SOLUTIONS INC.,2024-08-19 17:31:00,0001493152-24-033180,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:ShareBasedCompensa...,{'tag': 'us-gaap:ShareBasedCompensationArrange...,"{'extracted_value': '-600,000', 'calculated_va...",10q-tesi-20240630/Stock-basedCompensationDetai...,True,{'error_tags': {'tag': 'us-gaap:ShareBasedComp...
36,DQC.US.0015.4007,"2023-01-26 09:00:53,991 [DQC.US.0015.4007] us-...",2023-01-26,ERROR,DQC,15,1133421,NORTHROP GRUMMAN CORP /DE/,2023-01-26 08:32:00,0001133421-23-000006,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:DefinedBenefitPlan...,{'tag': 'us-gaap:DefinedBenefitPlanAssumptions...,"{'extracted_value': '-0.0554', 'calculated_val...",10k-noc-20221231/RetirementBenefitsPlanAssumpt...,True,{'error_tags': {'tag': 'us-gaap:DefinedBenefit...
88,DQC.US.0015.6933,"2025-01-08 09:17:53,426 [DQC.US.0015.6933] us-...",2025-01-08,ERROR,DQC,15,1634117,"BARNES & NOBLE EDUCATION, INC.",2024-12-09 09:06:00,0001634117-24-000130,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:FinanceLeasePrinci...,{'tag': 'us-gaap:FinanceLeasePrincipalPayments...,"{'extracted_value': '-398,000', 'calculated_va...",10q-bned-20241026/StatementofCashFlowsStatement,True,{'error_tags': {'tag': 'us-gaap:FinanceLeasePr...
81,DQC.US.0015.2771,"2024-08-02 16:12:51,530 [DQC.US.0015.2771] us-...",2024-08-02,ERROR,DQC,15,1653653,"RED ROCK RESORTS, INC.",2024-02-21 14:28:00,0001653653-24-000004,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:UnrecognizedTaxBen...,{'tag': 'us-gaap:UnrecognizedTaxBenefitsDecrea...,"{'extracted_value': '-451,000', 'calculated_va...",10k-rrr-20231231/IncomeTaxesDetails,True,{'error_tags': {'tag': 'us-gaap:UnrecognizedTa...
94,DQC.US.0015.2932,"2024-11-18 06:10:55,263 [DQC.US.0015.2932] us-...",2024-11-18,ERROR,DQC,15,1527702,iQSTEL Inc.,2024-11-14 08:06:00,0001663577-24-000281,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:PaymentsToAcquireO...,{'tag': 'us-gaap:PaymentsToAcquireOtherProduct...,"{'extracted_value': '-189,767', 'calculated_va...",10q-iqst-20240930/ConsoolidatedStatementsOfCas...,True,{'error_tags': {'tag': 'us-gaap:PaymentsToAcqu...
34,DQC.US.0015.2419,"2023-01-26 09:00:53,995 [DQC.US.0015.2419] us-...",2023-01-26,ERROR,DQC,15,1133421,NORTHROP GRUMMAN CORP /DE/,2023-01-26 08:32:00,0001133421-23-000006,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:ShareBasedCompensa...,{'tag': 'us-gaap:ShareBasedCompensationArrange...,"{'extracted_value': '-269,000', 'calculated_va...",10k-noc-20221231/StockCompensationPlansStockAw...,True,{'error_tags': {'tag': 'us-gaap:ShareBasedComp...
4,DQC.US.0015.576,"2022-02-23 06:12:12,070 [DQC.US.0015.576] us-g...",2022-02-23,ERROR,DQC,15,1841666,APA Corp,2022-02-22 14:30:00,0001784031-22-000009,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:CostsIncurredAcqui...,{'tag': 'us-gaap:CostsIncurredAcquisitionOfOil...,"{'extracted_value': '-157,000,000', 'calculate...",10k-apa-20211231/SUPPLEMENTALOILANDGASDISCLOSU...,True,{'error_tags': {'tag': 'us-gaap:CostsIncurredA...
109,DQC.US.0015.2923,"2024-08-28 10:19:20,974 [DQC.US.0015.2923] us-...",2024-08-28,ERROR,DQC,15,1375793,"MetAlert, Inc.",2024-08-19 17:21:00,0001493152-24-033153,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:SellingAndMarketin...,"{'tag': 'us-gaap:SellingAndMarketingExpense', ...","{'extracted_value': '-20', 'calculated_value':...",10q-mlrt-20240630/StatementsOfOperations,True,{'error_tags': {'tag': 'us-gaap:SellingAndMark...
1,DQC.US.0015.1307,"2022-02-10 17:03:12,659 [DQC.US.0015.1307] us-...",2022-02-10,ERROR,DQC,15,1070412,CNX Resources Corporation,2022-02-10 16:20:00,0001070412-22-000011,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:IncomeTaxReconcili...,{'tag': 'us-gaap:IncomeTaxReconciliationTaxCre...,"{'extracted_value': '-2,881,000', 'calculated_...",10k-cnx-20211231/IncomeTaxesEffectiveTaxRateRe...,True,{'error_tags': {'tag': 'us-gaap:IncomeTaxRecon...
12,DQC.US.0015.1873,"2022-11-16 06:04:03,668 [DQC.US.0015.1873] us-...",2022-11-16,ERROR,DQC,15,1703073,VIVIC CORP.,2022-11-14 16:27:00,0001549727-22-000093,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:OtherExpenses\nLab...,"{'tag': 'us-gaap:OtherExpenses', 'period': '20...","{'extracted_value': '-52,292', 'calculated_val...",10q-vivc-20220930/UnauditedCondensedConsolidat...,True,{'error_tags': {'tag': 'us-gaap:OtherExpenses'...
7,DQC.US.0015.579,"2022-12-29 16:45:43,438 [DQC.US.0015.579] us-g...",2022-12-29,ERROR,DQC,15,10048,"BARNWELL INDUSTRIES, INC.",2022-12-29 16:12:00,0000010048-22-000029,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:CostsIncurredOilAn...,{'tag': 'us-gaap:CostsIncurredOilAndGasPropert...,"{'extracted_value': '-121,000', 'calculated_va...",10k-brn-20220930/SUPPLEMENTARYOILANDNATURALGAS...,True,{'error_tags': {'tag': 'us-gaap:CostsIncurredO...

In [5]:
df_0117

,assertion.code,assertion.detail,assertion.run-date,assertion.severity,assertion.source,assertion.type,entity.cik,entity.name,report.accepted-timestamp,report.accession,...,calculation,definition,label,instance,us_gaap,input,true_answer,segmentation_path,parse_successful,LLM_Output
5,DQC.US.0117.9574,"2022-02-17 07:02:22,180 [DQC.US.0117.9574] In ...",2022-02-17,ERROR,DQC,117,92122,The Southern Company,2022-02-16 17:44:00,0000092122-22-000003,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:Revenues\nLabel: R...,"{'tag': 'us-gaap:Revenues', 'period': '2021-01...","{'extracted_value': '23,113,000,000', 'calcula...",10k-so-20211231/StatementsofIncomeGPC,True,{'statement_name': 'Statements of Income - APC...
47,DQC.US.0117.9574,"2023-05-16 19:26:38,277 [DQC.US.0117.9574] In ...",2023-05-16,ERROR,DQC,117,1172178,LIBERTY STAR URANIUM & METALS CORP.,2023-05-15 21:29:00,0001493152-23-017610,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:CommonStockValue\n...,"{'tag': 'us-gaap:CommonStockValue', 'period': ...","{'extracted_value': '186', 'calculated_value':...",10k-lbsr-20230131/BalanceSheets,True,{'statement_name': 'Consolidated Balance Sheet...
112,DQC.US.0117.9574,"2024-11-05 18:55:47,920 [DQC.US.0117.9574] In ...",2024-11-05,ERROR,DQC,117,1357878,"REGENEREX PHARMA, INC.",2024-11-04 11:44:00,0001472375-24-000090,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:LongTermDebtNoncur...,"{'tag': 'us-gaap:LongTermDebtNoncurrent', 'per...","{'extracted_value': '184,232', 'calculated_val...",10q-rgpx-20240930/BalanceSheets,True,{'statement_name': 'BALANCE SHEETS (UNAUDITED)...
58,DQC.US.0117.9574,"2023-08-14 12:39:41,230 [DQC.US.0117.9574] In ...",2023-08-14,ERROR,DQC,117,356590,"Global Tech Industries Group, Inc.",2023-08-14 11:56:00,0001493152-23-028169,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:AccountsPayableAnd...,{'tag': 'us-gaap:AccountsPayableAndAccruedLiab...,"{'extracted_value': '952,507', 'calculated_val...",10q-gtii-20230630/BalanceSheets,True,{'statement_name': 'Consolidated Balance Sheet...
60,DQC.US.0117.9574,"2024-01-19 17:47:03,034 [DQC.US.0117.9574] In ...",2024-01-19,ERROR,DQC,117,1502152,GlobeStar Therapeutics Corp,2024-01-19 17:13:00,0001161697-24-000049,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:StockholdersEquity...,"{'tag': 'us-gaap:StockholdersEquity', 'period'...","{'extracted_value': '-1,433,861', 'calculated_...",10k-gstc-20230930/ConsolidatedBalanceSheets,True,{'statement_name': 'CONSOLIDATED BALANCE SHEET...
88,DQC.US.0117.9574,"2024-05-17 17:01:46,783 [DQC.US.0117.9574] In ...",2024-05-17,ERROR,DQC,117,860543,Jacksam Corporation,2024-05-17 16:00:00,0001477932-24-003114,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:PreferredStockValu...,"{'tag': 'us-gaap:PreferredStockValue', 'period...","{'extracted_value': '0', 'calculated_value': '...",10q-jksm-20240331/CondensedConsolidatedBalance...,True,{'statement_name': 'Condensed Consolidated Bal...
115,DQC.US.0117.9574,"2024-11-19 13:17:18,105 [DQC.US.0117.9574] In ...",2024-11-19,ERROR,DQC,117,1563568,"ENVIROTECH VEHICLES, INC.",2024-11-14 16:15:00,0001437749-24-035310,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:LongTermDebt\nLabe...,"{'tag': 'us-gaap:LongTermDebt', 'period': '202...","{'extracted_value': '918,063', 'calculated_val...",10q-evtv-20240930/statement-consolidated-balan...,True,{'statement_name': '001 - Statement - Consolid...
20,DQC.US.0117.9574,"2022-02-25 09:17:47,579 [DQC.US.0117.9574] In ...",2022-02-25,ERROR,DQC,117,805676,PARK NATIONAL CORPORATION,2022-02-24 16:16:00,0000805676-22-000034,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:NoninterestIncomeO...,"{'tag': 'us-gaap:NoninterestIncomeOther', 'per...","{'extracted_value': '10,551,000', 'calculated_...",10k-prk-20211231/ConsolidatedStatementsofIncome,True,{'statement_name': 'Consolidated Statements of...
113,DQC.US.0117.9574,"2024-11-18 21:31:52,872 [DQC.US.0117.9574] In ...",2024-11-19,ERROR,DQC,117,1081938,"CannaPharmaRX, Inc.",2024-11-13 17:46:00,0001654954-24-014287,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:PreferredStockValu...,"{'tag': 'us-gaap:PreferredStockValue', 'period...","{'extracted_value': '2,455,000', 'calculated_v...",10q-celz-20240930/CondensedConsolidatedBalance...,True,{'statement_name': 'CONDENSED CONSOLIDATED BAL...
61,DQC.US.0117.9574,"2024-01-19 17:47:03,034 [DQC.US.0117.9574] In ...",2024-01-19,ERROR,DQC,117,1502152,GlobeStar Therapeutics Corp,2024-01-19 17:13:00,0001161697-24-000049,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:StockholdersEquity...,"{'tag': 'us-gaap:StockholdersEquity', 'period'...","{'extracted_value': '-725,821', 'calculated_va...",10k-gstc-20230930/ConsolidatedBalanceSheets,True,{'statement_name': 'CONSOLIDATED BALANCE SHEET...
33,DQC.US.0117.9574,"2022-10-19 17:00:37,807 [DQC.US.0117.9574] In ...",2022-10-19,ERROR,DQC,117,319458,Enservco Corporation,2022-10-19 16:26:00,0001437749-22-024387,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:DepreciationAndAmo...,"{'tag': 'us-gaap:DepreciationAndAmortization',...","{'extracted_value': '1,336,000', 'calculated_v...",10q-ensv-20220331/statement-condensed-consolid...,True,{'statement_name': 'Condensed Consolidated Sta...
73,DQC.US.0117.9574,"2024-03-25 17:51:50,996 [DQC.US.0117.9574] In ...",2024-03-25,ERROR,DQC,117,1847874,MOBILE INFRASTRUCTURE CORPORATION,2024-03-22 08:56:00,0001437749-24-008931,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:GainsLossesOnExtin...,{'tag': 'us-gaap:GainsLossesOnExtinguishmentOf...,"{'extracted_value': '0', 'calculated_value': '...",10k-beep-20231231/statement-consolidated-state...,True,{'statement_name': '006 - Statement - Consolid...
66,DQC.US.0117.9574,"2024-03-12 07:04:46,635 [DQC.US.0117.9574] In ...",2024-03-12,ERROR,DQC,117,1502152,GlobeStar Therapeutics Corp,2024-03-11 18:47:00,0001161697-24-000130,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:StockholdersEquity...,"{'tag': 'us-gaap:StockholdersEquity', 'period'...","{'extracted_value': '-1,194,560', 'calculated_...",10q-gstc-20231231/ConsolidatedBalanceSheets,True,{'statement_name': 'CONSOLIDATED BALANCE SHEET...
25,DQC.US.0117.9574,"2022-04-28 08:47:19,100 [DQC.US.0117.9574] In ...",2022-04-28,ERROR,DQC,117,4904,"AMERICAN ELECTRIC POWER COMPANY, INC.",2022-04-28 07:07:00,0000004904-22-000053,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:Revenues\nLabel: R...,"{'tag': 'us-gaap:Revenues', 'period': '2021-01...","{'extracted_value': '4,281,100,000', 'calculat...",10q-aep-20220331/ConsolidatedStatementsofIncome,True,{'statement_name': 'Consolidated Statements of...
105,DQC.US.0117.9574,"2024-10-11 09:48:32,608 [DQC.US.0117.9574] In ...",2024-10-11,ERROR,DQC,117,1502152,GlobeStar Therapeutics Corp,2024-10-11 09:08:00,0001161697-24-000420,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:StockholdersEquity...,"{'tag': 'us-gaap:StockholdersEquity', 'period'...","{'extracted_value': '-1,468,649', 'calculated_...",10q-gstc-20240630/ConsolidatedBalanceSheets,True,{'statement_name': 'CONSOLIDATED BALANCE SHEET...
98,DQC.US.0117.9574,"2024-08-09 11:48:41,393 [DQC.US.0117.9574] In ...",2024-08-09,ERROR,DQC,117,1357878,"REGENEREX PHARMA, INC.",2024-08-07 12:13:00,0001472375-24-000074,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:NotesPayableCurren...,"{'tag': 'us-gaap:NotesPayableCurrent', 'period...","{'extracted_value': '2,400,000', 'calculated_v...",10q-rgpx-20240630/BalanceSheets,True,{'statement_name': 'BALANCE SHEETS (UNAUDITED)...
76,DQC.US.0117.9574,"2024-05-16 18:18:04,615 [DQC.US.0117.9574] In ...",2024-05-16,ERROR,DQC,117,814926,"CAPSTONE COMPANIES, INC.",2024-03-29 17:24:00,0001903596-24-000189,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:StockholdersEquity...,"{'tag': 'us-gaap:StockholdersEquity', 'period'...","{'extracted_value': '-2,241,820', 'calculated_...",10k-capc-20231231/StockTransaction,True,{'statement_name': 'CONSOLIDATED BALANCE SHEET...
0,DQC.US.0117.9574,"2022-02-07 17:45:51,654 [DQC.US.0117.9574] In ...",2022-02-07,ERROR,DQC,117,913760,StoneX Group Inc.,2022-02-07 17:24:00,0000913760-22-000029,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:RevenueFromContrac...,{'tag': 'us-gaap:RevenueFromContractWithCustom...,"{'extracted_value': '255,500,000', 'calculated...",10q-intl-20211231/CondensedConsolidatedIncomeS...,True,{'statement_name': 'Condensed Consolidated Inc...
94,DQC.US.0117.9574,"2024-06-28 20:22:57,891 [DQC.US.0117.9574] In ...",2024-06-29,ERROR,DQC,117,1502152,GlobeStar Therapeutics Corp,2024-06-28 17:08:00,0001161697-24-000285,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:StockholdersEquity...,"{'tag': 'us-gaap:StockholdersEquity', 'period'...","{'extracted_value': '-1,532,533', 'calculated_...",10q-gstc-20240331/ConsolidatedBalanceSheets,True,{'statement_name': 'CONSOLIDATED BALANCE SHEET...
96,DQC.US.0117.9574,"2024-06-28 20:22:57,892 [DQC.US.0117.9574] In ...",2024-06-29,ERROR,DQC,117,1502152,GlobeStar Therapeutics Corp,2024-06-28 17:08:00,0001161697-24-000285,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:StockholdersEquity...,"{'tag': 'us-gaap:StockholdersEquity', 'period'...","{'extracted_value': '-1,468,649', 'calculated_...",10q-gstc-20240331/ConsolidatedBalanceSheets,True,{'statement_name': 'CONSOLIDATED BALANCE SHEET...
70,DQC.US.0117.9574,"2024-03-18 17:02:09,011 [DQC.US.0117.9574] In ...",2024-03-18,ERROR,DQC,117,1377630,"NATIONAL CINEMEDIA, INC.",2024-03-18 16:23:00,0001377630-24-000042,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,NaN,"{'tag': 'ncmi:TheaterAccessFees', 'period': '2...","{'extracted_value': '43,100,000', 'calculated_...",10k-ncmi-20231228/RelatedPartyTransactionsSche...,True,{'statement_name': 'CONSOLIDATED STATEMENTS OF...
103,DQC.US.0117.9574,"2024-10-11 09:48:32,608 [DQC.US.0117.9574] In ...",2024-10-11,ERROR,DQC,117,1502152,GlobeStar Therapeutics Corp,2024-10-11 09:08:00,0001161697-24-000420,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:StockholdersEquity...,"{'tag': 'us-gaap:StockholdersEquity', 'period'...","{'extracted_value': '-1,277,133', 'calculated_...",10q-gstc-20240630/ConsolidatedBalanceSheets,True,{'statement_name': 'CONSOLIDATED BALANCE SHEET...
108,DQC.US.0117.9574,"2024-10-11 09:48:32,609 [DQC.US.0117.9574] In ...",2024-10-11,ERROR,DQC,117,1502152,GlobeStar Therapeutics Corp,2024-10-11 09:08:00,0001161697-24-000420,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:StockholdersEquity...,"{'tag': 'us-gaap:StockholdersEquity', 'period'...","{'extracted_value': '-1,237,566', 'calculated_...",10q-gstc-20240630/ConsolidatedBalanceSheets,True,{'statement_name': 'CONSOLIDATED BALANCE SHEET...
69,DQC.US.0117.9574,"2024-03-12 07:04:46,636 [DQC.US.0117.9574] In ...",2024-03-12,ERROR,DQC,117,1502152,GlobeStar Therapeutics Corp,2024-03-11 18:47:00,0001161697-24-000130,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:StockholdersEquity...,"{'tag': 'us-gaap:StockholdersEquity', 'period'...","{'extracted_value': '-1,532,533', 'calculated_...",10q-gstc-20231231/ConsolidatedBalanceSheets,True,{'statement_name': 'CONSOLIDATED BALANCE SHEET...
55,DQC.US.0117.9574,"2023-08-18 16:47:01,657 [DQC.US.0117.9574] In ...",2023-08-18,ERROR,DQC,117,63330,"MAUI LAND & PINEAPPLE COMPANY, INC.",2023-08-18 16:00:00,0001437749-23-024158,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:RevenueFromContrac...,{'tag': 'us-gaap:RevenueFromContractWithCustom...,"{'extracted_value': '19,000', 'calculated_valu...",10q-mlp-20230630/statement-condensed-consolida...,True,{'statement_name': 'Condensed Consolidated Sta...
34,DQC.US.0117.9574,"2023-02-03 19:01:03,190 [DQC.US.0117.9574] In ...",2023-02-04,ERROR,DQC,117,704172,"PHI GROUP, INC.",2023-02-03 16:45:00,0001493152-23-003538,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:PreferredStockValu...,"{'tag': 'us-gaap:PreferredStockValue', 'period...","{'extracted_value': '2,440', 'calculated_value...",10q-phil-20220930/BalanceSheets,True,{'statement_name': 'Consolidated Balance Sheet...
74,DQC.US.0117.9574,"2024-03-25 17:51:50,996 [DQC.US.0117.9574] In ...",2024-03-25,ERROR,DQC,117,1847874,MOBILE INFRASTRUCTURE CORPORATION,2024-03-22 08:56:00,0001437749-24-008931,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:GainsLossesOnExtin...,{'tag': 'us-gaap:GainsLossesOnExtinguishmentOf...,"{'extracted_value': '328,000', 'calculated_val...",10k-beep-20231231/statement-consolidated-state...,True,{'statement_name': '006 - Statement - Consolid...
75,DQC.US.0117.9574,"2024-05-16 18:18:04,615 [DQC.US.0117.9574] In ...",2024-05-16,ERROR,DQC,117,814926,"CAPSTONE COMPANIES, INC.",2024-03-29 17:24:00,0001903596-24-000189,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:StockholdersEquity...,"{'tag': 'us-gaap:StockholdersEquity', 'period'...","{'extracted_value': '2,122,188', 'calculated_v...",10k-capc-20231231/StockTransaction,True,{'statement_name': 'CONSOLIDATED BALANCE SHEET...
77,DQC.US.0117.9574,"2024-05-16 18:18:04,616 [DQC.US.0117.9574] In ...",2024-05-16,ERROR,DQC,117,814926,"CAPSTONE COMPANIES, INC.",2024-03-29 17:24:00,0001903596-24-000189,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:StockholdersEquity...,"{'tag': 'us-gaap:StockholdersEquity', 'period'...","{'extracted_value': '-545,381', 'calculated_va...",10k-capc-20231231/StockTransaction,True,{'statement_name': 'CONSOLIDATED BALANCE SHEET...
107,DQC.US.0117.9574,"2024-10-11 09:48:32,609 [DQC.US.0117.9574] In ...",2024-10-11,ERROR,DQC,117,1502152,GlobeStar Therapeutics Corp,2024-10-11 09:08:00,0001161697-24-000420,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:StockholdersEquity...,"{'tag': 'us-gaap:StockholdersEquity', 'period'...","{'extracted_value': '-1,194,560', 'calculated_...",10q-gstc-20240630/ConsolidatedBalanceSheets,True,{'statement_name': 'CONSOLIDATED BALANCE SHEET...
57,DQC.US.0117.9574,"2023-08-14 12:39:41,229 [DQC.US.0117.9574] In ...",2023-08-14,ERROR,DQC,117,356590,"Global Tech Industries Group, Inc.",2023-08-14 11:56:00,0001493152-23-028169,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:AccountsPayableAnd...,{'tag': 'us-gaap:AccountsPayableAndAccruedLiab...,"{'extracted_value': '963,477', 'calculated_val...",10q-gtii-20230630/BalanceSheets,True,{'statement_name': 'Consolidated Balance Sheet...

In [6]:
# df_0117.at[0,"true_answer"]

In [7]:
# df_0117.at[0,"input"]

In [8]:
df_0126

,assertion.code,assertion.detail,assertion.run-date,assertion.severity,assertion.source,assertion.type,entity.cik,entity.name,report.accepted-timestamp,report.accession,...,calculation,definition,label,instance,us_gaap,input,true_answer,segmentation_path,parse_successful,LLM_Output
85,DQC.US.0126.9590,"2024-03-25 18:03:30,883 [DQC.US.0126.9590] The...",2024-03-25,ERROR,DQC,126,1309082,"Camber Energy, Inc.",2024-03-25 08:55:00,0001477932-24-001445,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:NetCashProvidedByU...,{'tag': 'us-gaap:NetCashProvidedByUsedInOperat...,"{'extracted_value': '-5,342,265', 'calculated_...",10k-cei-20231231/ConsolidatedStatementsOfCashF...,True,{'statement_name': 'CONSOLIDATED STATEMENTS OF...
94,DQC.US.0126.9590,"2024-11-18 06:31:56,664 [DQC.US.0126.9590] The...",2024-11-18,ERROR,DQC,126,55234,KENILWORTH SYSTEMS CORPORATION,2024-11-14 11:53:00,0001477932-24-007166,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:NetCashProvidedByU...,{'tag': 'us-gaap:NetCashProvidedByUsedInOperat...,"{'extracted_value': '-285,287', 'calculated_va...",10q-kenilworth-20240930/ConsolidatedStatementO...,True,{'statement_name': 'CONSOLIDATED STATEMENT OF ...
60,DQC.US.0126.9590,"2022-11-13 00:53:24,375 [DQC.US.0126.9590] The...",2022-11-13,ERROR,DQC,126,1408146,SCANDIUM INTERNATIONAL MINING CORP.,2022-11-10 15:51:00,0001654954-22-015016,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:OperatingExpenses\...,"{'tag': 'us-gaap:OperatingExpenses', 'period':...","{'extracted_value': '-614,011', 'calculated_va...",10q-scy-20220930/CondensedConsolidatedStatemen...,True,{'statement_name': 'CONDENSED CONSOLIDATED STA...
43,DQC.US.0126.9590,"2022-11-21 08:45:40,151 [DQC.US.0126.9590] The...",2022-11-21,ERROR,DQC,126,1389067,"ARtelligence Holdings, Inc.",2022-11-21 08:12:00,0001477932-22-008734,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:OtherOperatingInco...,{'tag': 'us-gaap:OtherOperatingIncomeExpenseNe...,"{'extracted_value': '-32002', 'calculated_valu...",10q-ttcm-20220930/ConsolidatedStatementsOfOper...,True,{'statement_name': 'CONSOLIDATED STATEMENTS OF...
12,DQC.US.0126.9590,"2022-03-03 17:47:14,835 [DQC.US.0126.9590] The...",2022-03-03,ERROR,DQC,126,1651562,"COURSERA, INC.",2022-03-03 16:18:00,0000950170-22-002807,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:StockholdersEquity...,"{'tag': 'us-gaap:StockholdersEquity', 'period'...","{'extracted_value': '741,513,000', 'calculated...",10k-cour-20211231/Role_StatementCondensedConso...,True,{'statement_name': 'Condensed Consolidated Bal...
18,DQC.US.0126.9590,"2022-03-07 17:00:45,494 [DQC.US.0126.9590] The...",2022-03-07,ERROR,DQC,126,1827075,CVENT HOLDING CORP.,2022-03-07 16:28:00,0000950170-22-003009,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:NetCashProvidedByU...,{'tag': 'us-gaap:NetCashProvidedByUsedInOperat...,"{'extracted_value': '122,196,000', 'calculated...",10k-cvt-20211231/Role_StatementConsolidatedSta...,True,{'statement_name': 'Consolidated Statements of...
6,DQC.US.0126.9590,"2022-02-23 06:46:31,672 [DQC.US.0126.9590] The...",2022-02-23,ERROR,DQC,126,862692,"CRYO-CELL INTERNATIONAL, INC.",2022-02-22 17:01:00,0000950170-22-001637,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:NetCashProvidedByU...,{'tag': 'us-gaap:NetCashProvidedByUsedInOperat...,"{'extracted_value': '7,926,094', 'calculated_v...",10k-ccel-20211130/Role_StatementConsolidatedSt...,True,{'statement_name': 'Consolidated Statements of...
24,DQC.US.0126.9590,"2022-03-11 18:02:47,504 [DQC.US.0126.9590] The...",2022-03-11,ERROR,DQC,126,1408146,SCANDIUM INTERNATIONAL MINING CORP.,2022-03-11 17:16:00,0001654954-22-003025,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:NetCashProvidedByU...,{'tag': 'us-gaap:NetCashProvidedByUsedInOperat...,"{'extracted_value': '374,205', 'calculated_val...",10k-scy-20211231/ConsolidatedStatementsOfCashF...,True,{'statement_name': 'CONSOLIDATED STATEMENTS OF...
21,DQC.US.0126.9590,"2022-03-09 17:49:56,010 [DQC.US.0126.9590] The...",2022-03-09,ERROR,DQC,126,1720116,"RED VIOLET, INC.",2022-03-09 16:56:00,0000950170-22-003240,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:NetCashProvidedByU...,{'tag': 'us-gaap:NetCashProvidedByUsedInOperat...,"{'extracted_value': '8,948,000', 'calculated_v...",10k-rdvt-20211231/StatementConsolidatedStateme...,True,{'statement_name': 'CONSOLIDATED STATEMENTS OF...
63,DQC.US.0126.9590,"2023-12-12 22:04:07,574 [DQC.US.0126.9590] The...",2023-12-13,ERROR,DQC,126,1616741,"PATRIOT\nTRANSPORTATION HOLDING, INC.",2023-12-12 15:49:00,0001616741-23-000042,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:NetCashProvidedByU...,{'tag': 'us-gaap:NetCashProvidedByUsedInFinanc...,"{'extracted_value': '117,000', 'calculated_val...",10k-pati-20230930/ConsolidatedStatementsOfCash...,True,{'statement_name': 'CONSOLIDATED STATEMENTS OF...
79,DQC.US.0126.9590,"2024-02-27 07:05:39,788 [DQC.US.0126.9590] The...",2024-02-27,ERROR,DQC,126,1678105,CARO HOLDINGS INC.,2024-02-26 19:08:00,0001640334-24-000301,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:NetCashProvidedByU...,{'tag': 'us-gaap:NetCashProvidedByUsedInOperat...,"{'extracted_value': '-212,200', 'calculated_va...",10q-caro-20231231/CondensedConsolidatedStateme...,True,{'statement_name': 'CONDENSED CONSOLIDATED STA...
78,DQC.US.0126.9590,"2024-02-14 19:52:15,157 [DQC.US.0126.9590] The...",2024-02-15,ERROR,DQC,126,1374881,Kingfish Holding Corporation,2024-02-14 17:13:00,0001477932-24-000736,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,NaN,"{'tag': 'king:TotalOperatingAndOtherExpenses',...","{'extracted_value': '56,480', 'calculated_valu...",10q-king-20231231/StatementsOfOperationsUnaudied,True,{'statement_name': 'STATEMENTS OF OPERATIONS (...
13,DQC.US.0126.9590,"2022-03-04 06:33:27,427 [DQC.US.0126.9590] The...",2022-03-04,ERROR,DQC,126,1576169,"BENEFITFOCUS, INC.",2022-03-03 19:40:00,0001564590-22-008597,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:LiabilitiesAndStoc...,{'tag': 'us-gaap:LiabilitiesAndStockholdersEqu...,"{'extracted_value': '260,841,000', 'calculated...",10k-bnft-20211231/StatementConsolidatedBalance...,True,{'statement_name': 'Consolidated Balance Sheet...
50,DQC.US.0126.9590,"2022-11-17 19:31:53,877 [DQC.US.0126.9590] The...",2022-11-18,ERROR,DQC,126,884650,"Infinite Group, Inc.",2022-11-17 16:30:00,0001654954-22-015502,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:NetCashProvidedByU...,{'tag': 'us-gaap:NetCashProvidedByUsedInInvest...,"{'extracted_value': '-166,405', 'calculated_va...",10q-imci-20220930/StatementsOfCashFlowsUnaudited,True,{'statement_name': 'STATEMENTS OF CASH FLOWS (...
67,DQC.US.0126.9590,"2023-11-20 15:35:40,555 [DQC.US.0126.9590] The...",2023-11-20,ERROR,DQC,126,1648903,"FIRST FOODS GROUP, INC.",2023-11-20 15:07:00,0001477932-23-008680,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:NetIncomeLossFromC...,{'tag': 'us-gaap:NetIncomeLossFromContinuingOp...,"{'extracted_value': '-609,959', 'calculated_va...",10q-fifg-20230930/CondensedConsolidatedStateme...,True,{'statement_name': 'Condensed Consolidated Sta...
92,DQC.US.0126.9590,"2024-11-19 15:17:30,533 [DQC.US.0126.9590] The...",2024-11-19,ERROR,DQC,126,1141197,PEDEVCO CORP.,2024-11-14 16:31:00,0001654954-24-014468,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:OtherNonoperatingI...,{'tag': 'us-gaap:OtherNonoperatingIncomeExpens...,"{'extracted_value': '295,000', 'calculated_val...",10q-ped-20240930/ConsolidatedStatementsOfOpera...,True,{'statement_name': 'CONSOLIDATED STATEMENTS OF...
10,DQC.US.0126.9590,"2022-02-25 15:16:58,406 [DQC.US.0126.9590] The...",2022-02-25,ERROR,DQC,126,704415,"TIVITY HEALTH, INC.",2022-02-25 14:31:00,0001564590-22-007093,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:NetCashProvidedByU...,{'tag': 'us-gaap:NetCashProvidedByUsedInOperat...,"{'extracted_value': '87,123,000', 'calculated_...",10k-tvty-20211231/StatementCONSOLIDATEDSTATEME...,True,{'statement_name': 'CONSOLIDATED STATEMENTS OF...
98,DQC.US.0126.9590,"2024-11-18 01:32:15,561 [DQC.US.0126.9590] The...",2024-11-18,ERROR,DQC,126,1309082,"Camber Energy, Inc.",2024-11-13 17:00:00,0001477932-24-007116,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:NetCashProvidedByU...,{'tag': 'us-gaap:NetCashProvidedByUsedInOperat...,"{'extracted_value': '-1,454,022', 'calculated_...",10q-cei-20240930/CondensedConsolidatedStatemen...,True,{'statement_name': 'Condensed Consolidated Sta...
49,DQC.US.0126.9590,"2022-11-21 06:30:45,317 [DQC.US.0126.9590] The...",2022-11-21,ERROR,DQC,126,1862068,"Rubicon Technologies, Inc.",2022-11-18 21:57:00,0001829126-22-019405,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:NetCashProvidedByU...,{'tag': 'us-gaap:NetCashProvidedByUsedInOperat...,"{'extracted_value': '-112,918,000', 'calculate...",10q-rbt-20220930/CondensedConsolidatedStatemen...,True,{'statement_name': 'CONDENSED CONSOLIDATED STA...
84,DQC.US.0126.9590,"2024-03-18 07:01:47,907 [DQC.US.0126.9590] The...",2024-03-18,ERROR,DQC,126,1141197,PEDEVCO CORP.,2024-03-15 18:45:00,0001654954-24-003240,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:NetCashProvidedByU...,{'tag': 'us-gaap:NetCashProvidedByUsedInOperat...,"{'extracted_value': '23,481,000', 'calculated_...",10k-ped-20231231/ConsolidatedStatementsOfCashF...,True,{'statement_name': 'CONSOLIDATED STATEMENTS OF...
91,DQC.US.0126.9590,"2024-11-19 15:17:30,532 [DQC.US.0126.9590] The...",2024-11-19,ERROR,DQC,126,1141197,PEDEVCO CORP.,2024-11-14 16:31:00,0001654954-24-014468,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:NetCashProvidedByU...,{'tag': 'us-gaap:NetCashProvidedByUsedInOperat...,"{'extracted_value': '8,547,000', 'calculated_v...",10q-ped-20240930/ConsolidatedStatementsOfCashF...,True,{'statement_name': 'CONSOLIDATED STATEMENTS OF...
71,DQC.US.0126.9590,"2024-01-23 14:46:40,646 [DQC.US.0126.9590] The...",2024-01-23,ERROR,DQC,126,1609258,PETROGAS COMPANY,2024-01-23 14:15:00,0001640334-24-000128,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:NetCashProvidedByU...,{'tag': 'us-gaap:NetCashProvidedByUsedInOperat...,"{'extracted_value': '-35,967', 'calculated_val...",10q-ptco-20231231/StatementOfCashFlowsUnaudited,True,{'statement_name': 'STATEMENT OF CASH FLOWS (U...
11,DQC.US.0126.9590,"2022-03-03 13:46:28,493 [DQC.US.0126.9590] The...",2022-03-03,ERROR,DQC,126,1690680,"Newmark Group, Inc.",2022-02-28 17:46:00,0001690680-22-000011,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,NaN,{'tag': 'nmrk:NetIncomeLossAfterAdjustmentsFor...,"{'extracted_value': '-300,897,000', 'calculate...",10k-nmrk-20211231/CONSOLIDATEDSTATEMENTSOFCASH...,True,{'statement_name': 'CONSOLIDATED STATEMENTS OF...
51,DQC.US.0126.9590,"2022-11-17 19:31:53,878 [DQC.US.0126.9590] The...",2022-11-18,ERROR,DQC,126,884650,"Infinite Group, Inc.",2022-11-17 16:30:00,0001654954-22-015502,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:NetCashProvidedByU...,{'tag': 'us-gaap:NetCashProvidedByUsedInOperat...,"{'extracted_value': '-699,104', 'calculated_va...",10q-imci-20220930/StatementsOfCashFlowsUnaudited,True,{'statement_name': 'STATEMENTS OF CASH FLOWS (...
69,DQC.US.0126.9590,"2023-11-14 23:06:23,227 [DQC.US.0126.9590] The...",2023-11-15,ERROR,DQC,126,1644488,SHARING SERVICES GLOBAL CORPORATION,2023-11-14 16:44:00,0001493152-23-041207,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:NonoperatingIncome...,"{'tag': 'us-gaap:NonoperatingIncomeExpense', '...","{'extracted_value': '-1082484', 'calculated_va...",10q-shrg-20230930/StatementsOfOperationsAndCom...,True,{'statement_name': 'Condensed Consolidated Sta...
62,DQC.US.0126.9590,"2023-02-14 15:32:06,985 [DQC.US.0126.9590] The...",2023-02-14,ERROR,DQC,126,1616741,"PATRIOT\nTRANSPORTATION HOLDING, INC.",2023-02-14 15:08:00,0001616741-23-000019,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:NetCashProvidedByU...,{'tag': 'us-gaap:NetCashProvidedByUsedInFinanc...,"{'extracted_value': '117,000', 'calculated_val...",10q-pati-20221231/ConsolidatedStatementsOfCash...,True,{'statement_name': 'CONSOLIDATED STATEMENTS OF...
64,DQC.US.0126.9590,"2023-11-20 16:47:43,801 [DQC.US.0126.9590] The...",2023-11-20,ERROR,DQC,126,1474167,COSMOS HEALTH INC.,2023-11-20 16:05:00,0001477932-23-008689,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:NetCashProvidedByU...,{'tag': 'us-gaap:NetCashProvidedByUsedInInvest...,"{'extracted_value': '-10,399,264', 'calculated...",10q-cosm-20230930/CondensedConsolidatedStateme...,True,{'statement_name': 'CONDENSED CONSOLIDATED STA...
80,DQC.US.0126.9590,"2024-03-13 12:16:15,385 [DQC.US.0126.9590] The...",2024-03-13,ERROR,DQC,126,1544400,NFiniTi inc.,2024-03-13 11:43:00,0001477932-24-001172,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:NetCashProvidedByU...,{'tag': 'us-gaap:NetCashProvidedByUsedInOperat...,"{'extracted_value': '-13,108', 'calculated_val...",10q-aoix-20240131/StatementsOfCashFlowsUnaudited,True,{'statement_name': 'Statements of Cash Flows (...
44,DQC.US.0126.9590,"2022-11-21 08:45:40,151 [DQC.US.0126.9590] The...",2022-11-21,ERROR,DQC,126,1389067,"ARtelligence Holdings, Inc.",2022-11-21 08:12:00,0001477932-22-008734,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:CashCashEquivalent...,{'tag': 'us-gaap:CashCashEquivalentsRestricted...,"{'extracted_value': '-115,117', 'calculated_va...",10q-ttcm-20220930/ConsolidatedStatementsOfCash...,True,{'statement_name': 'CONSOLIDATED STATEMENTS OF...
36,DQC.US.0126.9590,"2022-12-19 13:18:17,663 [DQC.US.0126.9590] The...",2022-12-19,ERROR,DQC,126,748268,"Red Cat Holdings, Inc.",2022-12-15 16:28:00,0001554795-22-000405,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:AssetsNoncurrent\n...,"{'tag': 'us-gaap:AssetsNoncurrent', 'period': ...","{'extracted_value': '30,227,410', 'calculated_...",10q-rcat-20221031/BalanceSheets,True,{'statement_name': 'Consolidated Balance Sheet...
0,DQC.US.0126.9590,"2022-03-04 20:32:57,578 [DQC.US.0126.9590] The...",2022-03-05,ERROR,DQC,126,1766352,"Carrier EQ, LLC",2022-01-21 19:05:00,0001553350-22-000052,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:NetCashProvidedByU...,{'tag': 'us-gaap:NetCashProvidedByUsedInOperat...,"{'extracted_value': '-4,771,555', 'calculated_...",10k-airfox-20210930/StatementsOfCashFlows,True,"{'statement_name': 'STATEMENTS OF CASH FLOWS',..."

In [9]:
system_prompt_MR = """You are an auditor for XBRL filings. 
Given the question and the provided filing 
(schema, presentation, calculation, definition, label, instance, and US GAAP taxonomy), 
identify the reported value of a financial element and calculate the actual value that should be reported based on calculation relationships.

Answer strictly in the following JSON format:
{
  "extracted_value": "<numeric value reported in the instance document, or 0 if not found, keep the same format as in the XBRL filing>",
  "calculated_value": "<numeric value computed from calculation relationships, or 0 if not computable, use the same number formatting style as extracted_value>"
}

No explanations. No extra text. Only the JSON object.
"""

In [10]:
def get_user_prompt(question1, question2, schema, presentation, calculation, definition, label, instance, taxonomy):
    prompt = f"""
##Schema document
{schema}

##Presentation linkbase document
{presentation}

##Calculation linkbase document
{calculation}

##Definition linkbase document
{definition}

##Label linkbase document
{label}

##Instance document
{instance}

##US GAAP Taxonomy
{taxonomy}

Question1: {question1}
Question2: {question2}
Answer:
"""

    return prompt

In [11]:
df_0015.columns

Index(['assertion.code', 'assertion.detail', 'assertion.run-date',
       'assertion.severity', 'assertion.source', 'assertion.type',
       'entity.cik', 'entity.name', 'report.accepted-timestamp',
       'report.accession', 'report.base-taxonomy', 'report.creation-software',
       'report.document-type', 'report.entry-url', 'report.filing-date',
       'report.filing-year', 'report.id', 'report.sec-url', 'report.sic-code',
       'folder_name', 'schema', 'presentation', 'calculation', 'definition',
       'label', 'instance', 'us_gaap', 'input', 'true_answer',
       'segmentation_path', 'parse_successful', 'LLM_Output'],
      dtype='object')

In [12]:
query = []
answer = []
dqc_id = []
for row in tqdm(df_0015.itertuples()):
    schema = row.schema 
    if pd.isna(schema):
        schema = "None"

    presentation = row.presentation
    if pd.isna(presentation):
        presentation = "None"

    calculation = row.calculation
    if pd.isna(calculation):
        calculation = "None"

    definition = row.definition
    if pd.isna(definition):
        definition = "None"

    label = row.label
    if pd.isna(label):
        label = "None"

    instance = row.instance
    if pd.isna(instance):
        instance = "None"

    taxonomy = row.us_gaap
    if pd.isna(taxonomy):
        taxonomy = "None"

    input = eval(row.input)
    
    question1 = f"""What's the reported value of {input.get('tag')} in the Instance document for the period {input.get('period')}?"""
    question2 = f"""What's the actual value of {input.get('tag')} in the Instance document for the period {input.get('period')}, calculated based on the calculation relationship?"""
    user_input = get_user_prompt(question1,question2,schema,presentation,calculation,definition,label,instance,taxonomy)
    
    q = f"""{system_prompt_MR}
{user_input}
"""
    a = eval(row.true_answer)
    a = {"extracted_value": a.get("extracted_value"), "calculated_value": a.get("calculated_value")}
    id = "DQC_US_0015"
    
    query.append(q)
    answer.append(a)
    dqc_id.append(id)

55it [00:00, 14701.85it/s]

In [13]:
for row in tqdm(df_0117.itertuples()):
    schema = row.schema 
    if pd.isna(schema):
        schema = "None"

    presentation = row.presentation
    if pd.isna(presentation):
        presentation = "None"

    calculation = row.calculation
    if pd.isna(calculation):
        calculation = "None"

    definition = row.definition
    if pd.isna(definition):
        definition = "None"

    label = row.label
    if pd.isna(label):
        label = "None"

    instance = row.instance
    if pd.isna(instance):
        instance = "None"

    taxonomy = row.us_gaap
    if pd.isna(taxonomy):
        taxonomy = "None"

    input = eval(row.input)
    
    question1 = f"""What's the reported value of {input.get('tag')} in the Instance document for the period {input.get('period')}?"""
    question2 = f"""What's the actual value of {input.get('tag')} in the Instance document for the period {input.get('period')}, calculated based on the calculation relationship?"""
    user_input = get_user_prompt(question1,question2,schema,presentation,calculation,definition,label,instance,taxonomy)
    
    q = f"""{system_prompt_MR}
{user_input}
"""
    a = eval(row.true_answer)
    a = {"extracted_value": a.get("extracted_value"), "calculated_value": a.get("calculated_value")}
    id = "DQC_US_0117"
    
    query.append(q)
    answer.append(a)
    dqc_id.append(id)

60it [00:00, 11100.94it/s]

In [14]:
for row in tqdm(df_0126.itertuples()):
    schema = row.schema 
    if pd.isna(schema):
        schema = "None"

    presentation = row.presentation
    if pd.isna(presentation):
        presentation = "None"

    calculation = row.calculation
    if pd.isna(calculation):
        calculation = "None"

    definition = row.definition
    if pd.isna(definition):
        definition = "None"

    label = row.label
    if pd.isna(label):
        label = "None"

    instance = row.instance
    if pd.isna(instance):
        instance = "None"

    taxonomy = row.us_gaap
    if pd.isna(taxonomy):
        taxonomy = "None"

    input = eval(row.input)
    
    question1 = f"""What's the reported value of {input.get('tag')} in the Instance document for the period {input.get('period')}?"""
    question2 = f"""What's the actual value of {input.get('tag')} in the Instance document for the period {input.get('period')}, calculated based on the calculation relationship?"""
    user_input = get_user_prompt(question1,question2,schema,presentation,calculation,definition,label,instance,taxonomy)
    
    q = f"""{system_prompt_MR}
{user_input}
"""
    a = eval(row.true_answer)
    a = {"extracted_value": a.get("extracted_value"), "calculated_value": a.get("calculated_value")}
    id = "DQC_US_0126"
    
    query.append(q)
    answer.append(a)
    dqc_id.append(id)

51it [00:00, 13014.69it/s]

In [15]:
df = pd.DataFrame({"query":query, "dqc_id": dqc_id, "answer":answer})

In [16]:
df

,query,dqc_id,answer
0,You are an auditor for XBRL filings. \nGiven t...,DQC_US_0015,"{'extracted_value': '-1,964,000,000', 'calcula..."
1,You are an auditor for XBRL filings. \nGiven t...,DQC_US_0015,"{'extracted_value': '-4,100,000', 'calculated_..."
2,You are an auditor for XBRL filings. \nGiven t...,DQC_US_0015,"{'extracted_value': '-4,200,000', 'calculated_..."
3,You are an auditor for XBRL filings. \nGiven t...,DQC_US_0015,"{'extracted_value': '-176,000', 'calculated_va..."
4,You are an auditor for XBRL filings. \nGiven t...,DQC_US_0015,"{'extracted_value': '-0.0258', 'calculated_val..."
...,...,...,...
161,You are an auditor for XBRL filings. \nGiven t...,DQC_US_0126,"{'extracted_value': '11,635,141', 'calculated_..."
162,You are an auditor for XBRL filings. \nGiven t...,DQC_US_0126,"{'extracted_value': '-105,060,000', 'calculate..."
163,You are an auditor for XBRL filings. \nGiven t...,DQC_US_0126,"{'extracted_value': '-25,312,000', 'calculated..."
164,You are an auditor for XBRL filings. \nGiven t...,DQC_US_0126,"{'extracted_value': '-247,587', 'calculated_va..."
165,You are an auditor for XBRL filings. \nGiven t...,DQC_US_0126,"{'extracted_value': '-213,667', 'calculated_va..."

In [17]:
df_json = df.applymap(json.dumps)

/tmp/ipykernel_698821/2966778623.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_json = df.applymap(json.dumps)

In [18]:
df_json

,query,dqc_id,answer
0,"""You are an auditor for XBRL filings. \nGiven ...","""DQC_US_0015""","{""extracted_value"": ""-1,964,000,000"", ""calcula..."
1,"""You are an auditor for XBRL filings. \nGiven ...","""DQC_US_0015""","{""extracted_value"": ""-4,100,000"", ""calculated_..."
2,"""You are an auditor for XBRL filings. \nGiven ...","""DQC_US_0015""","{""extracted_value"": ""-4,200,000"", ""calculated_..."
3,"""You are an auditor for XBRL filings. \nGiven ...","""DQC_US_0015""","{""extracted_value"": ""-176,000"", ""calculated_va..."
4,"""You are an auditor for XBRL filings. \nGiven ...","""DQC_US_0015""","{""extracted_value"": ""-0.0258"", ""calculated_val..."
...,...,...,...
161,"""You are an auditor for XBRL filings. \nGiven ...","""DQC_US_0126""","{""extracted_value"": ""11,635,141"", ""calculated_..."
162,"""You are an auditor for XBRL filings. \nGiven ...","""DQC_US_0126""","{""extracted_value"": ""-105,060,000"", ""calculate..."
163,"""You are an auditor for XBRL filings. \nGiven ...","""DQC_US_0126""","{""extracted_value"": ""-25,312,000"", ""calculated..."
164,"""You are an auditor for XBRL filings. \nGiven ...","""DQC_US_0126""","{""extracted_value"": ""-247,587"", ""calculated_va..."
165,"""You are an auditor for XBRL filings. \nGiven ...","""DQC_US_0126""","{""extracted_value"": ""-213,667"", ""calculated_va..."

## loading to hf

In [1]:
# hf_dataset = Dataset.from_pandas(df_json,preserve_index=True)
# hf_dataset = hf_dataset.rename_column("__index_level_0__", "id")

In [2]:
# hf_dataset

In [3]:
# dataset_repo = "TheFinAI/FinMR_Sub"

In [4]:
# hf_dataset.push_to_hub(dataset_repo,split="test",private=False)