In [2]:
import pandas as pd
import json
from tqdm.std import tqdm
import os

In [12]:
selected_task_file = "output_files/selected_output/selected_mathematical_reasoning_0015.xlsx"

index_prefix = {
    "2024": "create_chunk/US_GAAP_Taxonomy/gaap_chunks_2024/",
    "2023": "create_chunk/US_GAAP_Taxonomy/gaap_chunks_2023/",
    "2022": "create_chunk/US_GAAP_Taxonomy/gaap_chunks_2022/"
}

In [13]:
initial_task_df = pd.read_excel(selected_task_file)

In [14]:
initial_task_df

,assertion.code,assertion.detail,assertion.run-date,assertion.severity,assertion.source,assertion.type,entity.cik,entity.name,report.accepted-timestamp,report.accession,...,calculation,definition,label,instance,us_gaap,input,true_answer,segmentation_path,parse_successful,LLM_Output
0,DQC.US.0015.1964,"2022-01-14 17:30:24,842 [DQC.US.0015.1964] us-...",2022-01-14,ERROR,DQC,15,1883835,ESG Inc.,2022-01-14 16:59:00,0001520138-22-000017,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:PaymentsToAcquireP...,{'tag': 'us-gaap:PaymentsToAcquirePropertyPlan...,"{'extracted_value': '-1284', 'calculated_value...",10q-plasma-20211130/CondensedStatementOfCashFlows,True,{'error_tags': {'tag': 'us-gaap:PaymentsToAcqu...
1,DQC.US.0015.1307,"2022-02-10 17:03:12,659 [DQC.US.0015.1307] us-...",2022-02-10,ERROR,DQC,15,1070412,CNX Resources Corporation,2022-02-10 16:20:00,0001070412-22-000011,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:IncomeTaxReconcili...,{'tag': 'us-gaap:IncomeTaxReconciliationTaxCre...,"{'extracted_value': '-2,881,000', 'calculated_...",10k-cnx-20211231/IncomeTaxesEffectiveTaxRateRe...,True,{'error_tags': {'tag': 'us-gaap:IncomeTaxRecon...
2,DQC.US.0015.757,"2022-02-17 21:02:49,520 [DQC.US.0015.757] us-g...",2022-02-18,ERROR,DQC,15,23194,"COMSTOCK RESOURCES, INC.",2022-02-17 15:41:00,0000023194-22-000011,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:DerivativeAverageF...,{'tag': 'us-gaap:DerivativeAverageForwardPrice...,"{'extracted_value': '-0.16', 'calculated_value...",10k-crk-20211231/DerivativeFinancialInstrument...,True,{'error_tags': {'tag': 'us-gaap:DerivativeAver...
3,DQC.US.0015.576,"2022-02-23 06:12:12,069 [DQC.US.0015.576] us-g...",2022-02-23,ERROR,DQC,15,1841666,APA Corp,2022-02-22 14:30:00,0001784031-22-000009,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:CostsIncurredAcqui...,{'tag': 'us-gaap:CostsIncurredAcquisitionOfOil...,"{'extracted_value': '-157,000,000', 'calculate...",10k-apa-20211231/SUPPLEMENTALOILANDGASDISCLOSU...,True,{'error_tags': {'tag': 'us-gaap:CostsIncurredA...
4,DQC.US.0015.576,"2022-02-23 06:12:12,070 [DQC.US.0015.576] us-g...",2022-02-23,ERROR,DQC,15,1841666,APA Corp,2022-02-22 14:30:00,0001784031-22-000009,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:CostsIncurredAcqui...,{'tag': 'us-gaap:CostsIncurredAcquisitionOfOil...,"{'extracted_value': '-157,000,000', 'calculate...",10k-apa-20211231/SUPPLEMENTALOILANDGASDISCLOSU...,True,{'error_tags': {'tag': 'us-gaap:CostsIncurredA...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,DQC.US.0015.9957,"2024-11-05 18:17:36,656 [DQC.US.0015.9957] us-...",2024-11-05,ERROR,DQC,15,1051512,"TELEPHONE AND DATA SYSTEMS, INC.",2024-11-01 07:53:00,0001051512-24-000064,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:FinancingReceivabl...,{'tag': 'us-gaap:FinancingReceivableYearFourOr...,"{'extracted_value': '-1,000,000', 'calculated_...",10q-tds-20240930/EquipmentInstallmentPlansAllo...,True,{'error_tags': {'tag': 'us-gaap:FinancingRecei...
106,DQC.US.0015.2973,"2024-11-01 18:35:19,522 [DQC.US.0015.2973] us-...",2024-11-01,ERROR,DQC,15,39263,"Cullen/Frost Bankers, Inc.",2024-10-31 15:06:00,0000039263-24-000069,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:RestrictedStockExp...,"{'tag': 'us-gaap:RestrictedStockExpense', 'per...","{'extracted_value': '-1,369,000', 'calculated_...",10q-cfr-20240930/StockBasedCompensationStockBa...,True,{'error_tags': {'tag': 'us-gaap:RestrictedStoc...
107,DQC.US.0015.2973,"2024-11-01 18:35:19,522 [DQC.US.0015.2973] us-...",2024-11-01,ERROR,DQC,15,39263,"Cullen/Frost Bankers, Inc.",2024-10-31 15:06:00,0000039263-24-000069,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:RestrictedStockExp...,"{'tag': 'us-gaap:RestrictedStockExpense', 'per...","{'extracted_value': '-521,000', 'calculated_va...",10q-cfr-20240930/StockBasedCompensationStockBa...,True,{'error_tags': {'tag': 'us-gaap:RestrictedStoc...
108,DQC.US.0015.2419,"2024-08-26 17:21:53,045 [DQC.US.0015.2419] us-...",2024-08-26,ERROR,DQC,15,1514056,TITAN ENVIRONMENTAL SOLUTIONS INC.,2024-08-19 17:31:00,0001493152-24-033180,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:ShareBasedCompensa...,{'tag': 'us-gaap:ShareBasedCompensationArrange...,"{'extracted_value': '-600,000', 'calculated_va...",10q-tesi-20240630/Stock-basedCompensationDetai...,True,{'error_tags': {'tag': 'us-gaap:ShareBasedComp...
109,DQC.US.0015.2923,"2024-08-28 10:19:20,974 [DQC.US.0015.2923] us-...",2024-08-28,ERROR,DQC,15,1375793,"MetAlert, Inc.",2024-08-19 17:21:00,0001493152-24-033153,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:SellingAndMarketin...,"{'tag': 'us-gaap:SellingAndMarketingExpense', ...","{'extracted_value': '-20', 'calculated_value':...",10q-mlrt-20240630/StatementsOfOperations,True,{'error_tags': {'tag': 'us-gaap:SellingAndMark...

In [15]:
initial_task_df.at[0,"true_answer"]

"{'extracted_value': '-1284', 'calculated_value': '1284', 'is_correct': 'Yes'}"

In [23]:
initial_task_df.at[0,"input"]

"{'tag': 'us-gaap:PaymentsToAcquirePropertyPlantAndEquipment', 'period': '2021-09-01 to 2021-11-30'}"

In [16]:
initial_task_df.columns

Index(['assertion.code', 'assertion.detail', 'assertion.run-date',
       'assertion.severity', 'assertion.source', 'assertion.type',
       'entity.cik', 'entity.name', 'report.accepted-timestamp',
       'report.accession', 'report.base-taxonomy', 'report.creation-software',
       'report.document-type', 'report.entry-url', 'report.filing-date',
       'report.filing-year', 'report.id', 'report.sec-url', 'report.sic-code',
       'folder_name', 'schema', 'presentation', 'calculation', 'definition',
       'label', 'instance', 'us_gaap', 'input', 'true_answer',
       'segmentation_path', 'parse_successful', 'LLM_Output'],
      dtype='object')

In [17]:
# set(initial_task_df["report.filing-year"].tolist())

In [18]:
def find_chunk_by_concept(jsonl_file, query_concept_id):
    """
    给定一个 us-gaap concept_id，在 jsonl 文件中找到完全匹配的条目，
    并返回对应的 chunk_text
    :param jsonl_file: jsonl 文件路径
    :param query_concept_id: 例如 "us-gaap:CashAndDueFromBanks"
    :return: list of chunk_text
    """
    results = []
    with open(jsonl_file, "r", encoding="utf-8") as f:
        for line in f:
            try:
                obj = json.loads(line)
                # print(obj)
                if obj.get("concept_id") == query_concept_id:  # 完全匹配
                    # print(1)
                    results.append(obj.get("chunk_text"))
            except json.JSONDecodeError:
                continue
    return results

In [19]:
def extract_usgaap_segmentation(df, task_name="RE"):
    new_df = df.copy(deep=True)
    for idx in tqdm(range(len(new_df))):
        report_year = str(new_df.at[idx, "report.filing-year"])
        is_parse = new_df.at[idx, "parse_successful"]
        prefix_path = index_prefix[report_year]
        concept_file = os.path.join(prefix_path,"chunks_core.jsonl")
        relation_file = os.path.join(prefix_path, "chunks_relations.jsonl")
        query = []
        if task_name == "MR":
            query_str = new_df.at[idx, "input"]
            query_json = eval(query_str)
            query.append(query_json.get("tag"))
        elif task_name == "RE":
            query_str = new_df.at[idx, "true_answer"]
            query_json = eval(query_str)
            for a in query_json:
                query.extend([a[0], a[-1]])
        elif task_name == "SM":
            query_str = new_df.at[idx, "true_answer"]
            query_json = eval(query_str)
            for a in query_json:
                if "=" in a:
                    query.extend(a.split("="))
                else:
                    query.append(a)
        else:
            raise ValueError("The task name must be MR, RE, or SM.")
        # print(query)
        segments = []
        for q in query:
            # print(q)
            res = find_chunk_by_concept(concept_file,q)
            segments.extend(res)
        for q in query:
            res = find_chunk_by_concept(relation_file,q)
            segments.extend(res)

        new_df.at[idx, "us_gaap"] = "\n\n\n".join(segments)

    return new_df

In [20]:
new_df = extract_usgaap_segmentation(initial_task_df, task_name="MR")

100%|██████████| 110/110 [00:51<00:00,  2.12it/s]

In [22]:
new_df

,assertion.code,assertion.detail,assertion.run-date,assertion.severity,assertion.source,assertion.type,entity.cik,entity.name,report.accepted-timestamp,report.accession,...,calculation,definition,label,instance,us_gaap,input,true_answer,segmentation_path,parse_successful,LLM_Output
0,DQC.US.0015.1964,"2022-01-14 17:30:24,842 [DQC.US.0015.1964] us-...",2022-01-14,ERROR,DQC,15,1883835,ESG Inc.,2022-01-14 16:59:00,0001520138-22-000017,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:PaymentsToAcquireP...,{'tag': 'us-gaap:PaymentsToAcquirePropertyPlan...,"{'extracted_value': '-1284', 'calculated_value...",10q-plasma-20211130/CondensedStatementOfCashFlows,True,{'error_tags': {'tag': 'us-gaap:PaymentsToAcqu...
1,DQC.US.0015.1307,"2022-02-10 17:03:12,659 [DQC.US.0015.1307] us-...",2022-02-10,ERROR,DQC,15,1070412,CNX Resources Corporation,2022-02-10 16:20:00,0001070412-22-000011,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:IncomeTaxReconcili...,{'tag': 'us-gaap:IncomeTaxReconciliationTaxCre...,"{'extracted_value': '-2,881,000', 'calculated_...",10k-cnx-20211231/IncomeTaxesEffectiveTaxRateRe...,True,{'error_tags': {'tag': 'us-gaap:IncomeTaxRecon...
2,DQC.US.0015.757,"2022-02-17 21:02:49,520 [DQC.US.0015.757] us-g...",2022-02-18,ERROR,DQC,15,23194,"COMSTOCK RESOURCES, INC.",2022-02-17 15:41:00,0000023194-22-000011,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:DerivativeAverageF...,{'tag': 'us-gaap:DerivativeAverageForwardPrice...,"{'extracted_value': '-0.16', 'calculated_value...",10k-crk-20211231/DerivativeFinancialInstrument...,True,{'error_tags': {'tag': 'us-gaap:DerivativeAver...
3,DQC.US.0015.576,"2022-02-23 06:12:12,069 [DQC.US.0015.576] us-g...",2022-02-23,ERROR,DQC,15,1841666,APA Corp,2022-02-22 14:30:00,0001784031-22-000009,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:CostsIncurredAcqui...,{'tag': 'us-gaap:CostsIncurredAcquisitionOfOil...,"{'extracted_value': '-157,000,000', 'calculate...",10k-apa-20211231/SUPPLEMENTALOILANDGASDISCLOSU...,True,{'error_tags': {'tag': 'us-gaap:CostsIncurredA...
4,DQC.US.0015.576,"2022-02-23 06:12:12,070 [DQC.US.0015.576] us-g...",2022-02-23,ERROR,DQC,15,1841666,APA Corp,2022-02-22 14:30:00,0001784031-22-000009,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:CostsIncurredAcqui...,{'tag': 'us-gaap:CostsIncurredAcquisitionOfOil...,"{'extracted_value': '-157,000,000', 'calculate...",10k-apa-20211231/SUPPLEMENTALOILANDGASDISCLOSU...,True,{'error_tags': {'tag': 'us-gaap:CostsIncurredA...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,DQC.US.0015.9957,"2024-11-05 18:17:36,656 [DQC.US.0015.9957] us-...",2024-11-05,ERROR,DQC,15,1051512,"TELEPHONE AND DATA SYSTEMS, INC.",2024-11-01 07:53:00,0001051512-24-000064,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:FinancingReceivabl...,{'tag': 'us-gaap:FinancingReceivableYearFourOr...,"{'extracted_value': '-1,000,000', 'calculated_...",10q-tds-20240930/EquipmentInstallmentPlansAllo...,True,{'error_tags': {'tag': 'us-gaap:FinancingRecei...
106,DQC.US.0015.2973,"2024-11-01 18:35:19,522 [DQC.US.0015.2973] us-...",2024-11-01,ERROR,DQC,15,39263,"Cullen/Frost Bankers, Inc.",2024-10-31 15:06:00,0000039263-24-000069,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:RestrictedStockExp...,"{'tag': 'us-gaap:RestrictedStockExpense', 'per...","{'extracted_value': '-1,369,000', 'calculated_...",10q-cfr-20240930/StockBasedCompensationStockBa...,True,{'error_tags': {'tag': 'us-gaap:RestrictedStoc...
107,DQC.US.0015.2973,"2024-11-01 18:35:19,522 [DQC.US.0015.2973] us-...",2024-11-01,ERROR,DQC,15,39263,"Cullen/Frost Bankers, Inc.",2024-10-31 15:06:00,0000039263-24-000069,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:RestrictedStockExp...,"{'tag': 'us-gaap:RestrictedStockExpense', 'per...","{'extracted_value': '-521,000', 'calculated_va...",10q-cfr-20240930/StockBasedCompensationStockBa...,True,{'error_tags': {'tag': 'us-gaap:RestrictedStoc...
108,DQC.US.0015.2419,"2024-08-26 17:21:53,045 [DQC.US.0015.2419] us-...",2024-08-26,ERROR,DQC,15,1514056,TITAN ENVIRONMENTAL SOLUTIONS INC.,2024-08-19 17:31:00,0001493152-24-033180,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:ShareBasedCompensa...,{'tag': 'us-gaap:ShareBasedCompensationArrange...,"{'extracted_value': '-600,000', 'calculated_va...",10q-tesi-20240630/Stock-basedCompensationDetai...,True,{'error_tags': {'tag': 'us-gaap:ShareBasedComp...
109,DQC.US.0015.2923,"2024-08-28 10:19:20,974 [DQC.US.0015.2923] us-...",2024-08-28,ERROR,DQC,15,1375793,"MetAlert, Inc.",2024-08-19 17:21:00,0001493152-24-033153,...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='US-ASCII'?>\n<li...,<?xml version='1.0' encoding='UTF-8'?>\n<link:...,<?xml version='1.0' encoding='UTF-8'?>\n<xbrl ...,[Concept Core]\nID: us-gaap:SellingAndMarketin...,"{'tag': 'us-gaap:SellingAndMarketingExpense', ...","{'extracted_value': '-20', 'calculated_value':...",10q-mlrt-20240630/StatementsOfOperations,True,{'error_tags': {'tag': 'us-gaap:SellingAndMark...

In [251]:
print(new_df.at[0, "us_gaap"])

[Concept Core]
ID: us-gaap:BalanceSheetLocationAxis
Label: Balance Sheet Location [Axis]
Type: xbrli:stringItemType | Balance: None | PeriodType: duration | Abstract: True
Status: None | DeprecatedLabel: None | DeprecatedDate: None
Documentation:
Information by location on balance sheet (statement of financial position).

Provenance: file=GAAP_Taxonomy_2022.xlsx | sheet=Concepts | row=1103


[Concept Relations]
ID: us-gaap:BalanceSheetLocationAxis

Presentation:
- Role: http://fasb.org/us-gaap/role/statement/CommonDomainMembers
  Path: Statement [Table] > Balance Sheet Location [Axis]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/statement/CommonDomainMembers
  Path: Balance Sheet Location [Axis] > Balance Sheet Location [Domain]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/BusinessCombinations
  Path: Business Combination, Separately Recognized Transactions [Table] > Balance Sheet Location [Axis]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/BusinessCombinations
  Path: Balance Sheet Location [Axis] > Balance Sheet Location [Domain]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/CommitmentAndContingencies
  Path: Loss Contingencies [Table] > Balance Sheet Location [Axis]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/CommitmentAndContingencies
  Path: Balance Sheet Location [Axis] > Balance Sheet Location [Domain]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/CommitmentAndContingencies
  Path: Product Liability Contingency [Table] > Balance Sheet Location [Axis]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/CommitmentAndContingencies
  Path: Balance Sheet Location [Axis] > Balance Sheet Location [Domain]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/CommitmentAndContingencies
  Path: Registration Payment Arrangement [Table] > Balance Sheet Location [Axis]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/CommitmentAndContingencies
  Path: Balance Sheet Location [Axis] > Balance Sheet Location [Domain]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/CompensationRelatedCostsStockCompensation
  Path: Share-Based Payment Arrangement, Expensed and Capitalized, Amount [Table] > Balance Sheet Location [Axis]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/CompensationRelatedCostsStockCompensation
  Path: Balance Sheet Location [Axis] > Balance Sheet Location [Domain]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/FinancialServicesBrokersAndDealers
  Path: Customer Securities for which Entity has Right to Sell or Repledge [Table] > Balance Sheet Location [Axis]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/FinancialServicesBrokersAndDealers
  Path: Balance Sheet Location [Axis] > Balance Sheet Location [Domain]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/EnvironmentalRemediationObligations
  Path: Recorded Third-Party Environmental Recoveries [Table] > Balance Sheet Location [Axis]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/EnvironmentalRemediationObligations
  Path: Balance Sheet Location [Axis] > Balance Sheet Location [Domain]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/EnvironmentalRemediationObligations
  Path: Site Contingency [Table] > Balance Sheet Location [Axis]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/EnvironmentalRemediationObligations
  Path: Balance Sheet Location [Axis] > Balance Sheet Location [Domain]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/Debt
  Path: Obligation with Joint and Several Liability Arrangement [Table] > Balance Sheet Location [Axis]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/Debt
  Path: Balance Sheet Location [Axis] > Balance Sheet Location [Domain]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/DerivativeInstrumentsAndHedgingActivities
  Path: Fair Values Derivatives, Balance Sheet Location, by Derivative Contract Type [Table] > Balance Sheet Location [Axis]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/DerivativeInstrumentsAndHedgingActivities
  Path: Balance Sheet Location [Axis] > Balance Sheet Location [Domain]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/DerivativeInstrumentsAndHedgingActivities
  Path: Foreign Currency Fair Value Hedge Derivative [Table] > Balance Sheet Location [Axis]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/DerivativeInstrumentsAndHedgingActivities
  Path: Balance Sheet Location [Axis] > Balance Sheet Location [Domain]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/DerivativeInstrumentsAndHedgingActivities
  Path: Price Risk Derivatives [Table] > Balance Sheet Location [Axis]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/DerivativeInstrumentsAndHedgingActivities
  Path: Balance Sheet Location [Axis] > Balance Sheet Location [Domain]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/DerivativeInstrumentsAndHedgingActivities
  Path: Schedule of Credit Derivatives [Table] > Balance Sheet Location [Axis]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/DerivativeInstrumentsAndHedgingActivities
  Path: Balance Sheet Location [Axis] > Balance Sheet Location [Domain]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/DerivativeInstrumentsAndHedgingActivities
  Path: Hybrid Instruments [Table] > Balance Sheet Location [Axis]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/DerivativeInstrumentsAndHedgingActivities
  Path: Balance Sheet Location [Axis] > Balance Sheet Location [Domain]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/DerivativeInstrumentsAndHedgingActivities
  Path: Embedded Derivative [Table] > Balance Sheet Location [Axis]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/DerivativeInstrumentsAndHedgingActivities
  Path: Balance Sheet Location [Axis] > Balance Sheet Location [Domain]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/ForeignOperationsAndCurrencyTranslation
  Path: Schedule of Differences between Reported Amount and Reporting Currency Denominated Amount [Table] > Balance Sheet Location [Axis]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/ForeignOperationsAndCurrencyTranslation
  Path: Balance Sheet Location [Axis] > Balance Sheet Location [Domain]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/TransfersAndServicing
  Path: Customer Securities for which Entity has Right to Sell or Repledge [Table] > Balance Sheet Location [Axis]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/TransfersAndServicing
  Path: Balance Sheet Location [Axis] > Balance Sheet Location [Domain]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/Guarantees
  Path: Schedule of Guarantor Obligations [Table] > Balance Sheet Location [Axis]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/Guarantees
  Path: Balance Sheet Location [Axis] > Balance Sheet Location [Domain]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/Guarantees
  Path: Product Warranty Liability [Table] > Balance Sheet Location [Axis]
  PreferredLabel: None
- Role: http://fasb.org/us-gaap/role/disclosure/Guarantees
  Path: Balance Sheet Location [Axis] > Balance Sheet Location [Domain]
  PreferredLabel: None
Provenance: sheets include Presentation-like sheets


[Concept Relations]
ID: us-gaap:BalanceSheetLocationAxis

Definition (Dimensions/Domain/Hypercube):
- http://xbrl.org/int/dim/arcrole/hypercube-dimension: from=us-gaap:StatementTable -> to=us-gaap:BalanceSheetLocationAxis (role=http://fasb.org/us-gaap/role/statement/CommonDomainMembersStatementTable)
- http://xbrl.org/int/dim/arcrole/dimension-default: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/statement/CommonDomainMembersStatementTable)
- http://xbrl.org/int/dim/arcrole/dimension-domain: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/statement/CommonDomainMembersStatementTable)
- http://xbrl.org/int/dim/arcrole/hypercube-dimension: from=us-gaap:ProductLiabilityContingencyTable -> to=us-gaap:BalanceSheetLocationAxis (role=http://fasb.org/us-gaap/role/disclosure/CommitmentAndContingenciesProductLiabilityContingencyTable)
- http://xbrl.org/int/dim/arcrole/dimension-default: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/disclosure/CommitmentAndContingenciesProductLiabilityContingencyTable)
- http://xbrl.org/int/dim/arcrole/dimension-domain: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/disclosure/CommitmentAndContingenciesProductLiabilityContingencyTable)
- http://xbrl.org/int/dim/arcrole/hypercube-dimension: from=us-gaap:SiteContingencyTable -> to=us-gaap:BalanceSheetLocationAxis (role=http://fasb.org/us-gaap/role/disclosure/EnvironmentalRemediationObligationsSiteContingencyTable)
- http://xbrl.org/int/dim/arcrole/dimension-default: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/disclosure/EnvironmentalRemediationObligationsSiteContingencyTable)
- http://xbrl.org/int/dim/arcrole/dimension-domain: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/disclosure/EnvironmentalRemediationObligationsSiteContingencyTable)
- http://xbrl.org/int/dim/arcrole/hypercube-dimension: from=us-gaap:LossContingenciesTable -> to=us-gaap:BalanceSheetLocationAxis (role=http://fasb.org/us-gaap/role/disclosure/CommitmentAndContingenciesLossContingenciesTable)
- http://xbrl.org/int/dim/arcrole/dimension-default: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/disclosure/CommitmentAndContingenciesLossContingenciesTable)
- http://xbrl.org/int/dim/arcrole/dimension-domain: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/disclosure/CommitmentAndContingenciesLossContingenciesTable)
- http://xbrl.org/int/dim/arcrole/hypercube-dimension: from=us-gaap:RegistrationPaymentArrangementTable -> to=us-gaap:BalanceSheetLocationAxis (role=http://fasb.org/us-gaap/role/disclosure/CommitmentAndContingenciesRegistrationPaymentArrangementTable)
- http://xbrl.org/int/dim/arcrole/dimension-default: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/disclosure/CommitmentAndContingenciesRegistrationPaymentArrangementTable)
- http://xbrl.org/int/dim/arcrole/dimension-domain: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/disclosure/CommitmentAndContingenciesRegistrationPaymentArrangementTable)
- http://xbrl.org/int/dim/arcrole/hypercube-dimension: from=us-gaap:ObligationWithJointAndSeveralLiabilityArrangementTable -> to=us-gaap:BalanceSheetLocationAxis (role=http://fasb.org/us-gaap/role/disclosure/DebtObligationWithJointAndSeveralLiabilityArrangementTable)
- http://xbrl.org/int/dim/arcrole/dimension-default: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/disclosure/DebtObligationWithJointAndSeveralLiabilityArrangementTable)
- http://xbrl.org/int/dim/arcrole/dimension-domain: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/disclosure/DebtObligationWithJointAndSeveralLiabilityArrangementTable)
- http://xbrl.org/int/dim/arcrole/hypercube-dimension: from=us-gaap:ScheduleOfEmployeeServiceShareBasedCompensationAllocationOfRecognizedPeriodCostsTable -> to=us-gaap:BalanceSheetLocationAxis (role=http://fasb.org/us-gaap/role/disclosure/CompensationRelatedCostsStockCompensationScheduleOfEmployeeServiceShareBasedCompensationAllocationOfRecognizedPeriodCostsTable)
- http://xbrl.org/int/dim/arcrole/dimension-default: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/disclosure/CompensationRelatedCostsStockCompensationScheduleOfEmployeeServiceShareBasedCompensationAllocationOfRecognizedPeriodCostsTable)
- http://xbrl.org/int/dim/arcrole/dimension-domain: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/disclosure/CompensationRelatedCostsStockCompensationScheduleOfEmployeeServiceShareBasedCompensationAllocationOfRecognizedPeriodCostsTable)
- http://xbrl.org/int/dim/arcrole/hypercube-dimension: from=us-gaap:BusinessCombinationSeparatelyRecognizedTransactionsTable -> to=us-gaap:BalanceSheetLocationAxis (role=http://fasb.org/us-gaap/role/disclosure/BusinessCombinationsBusinessCombinationSeparatelyRecognizedTransactionsTable)
- http://xbrl.org/int/dim/arcrole/dimension-default: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/disclosure/BusinessCombinationsBusinessCombinationSeparatelyRecognizedTransactionsTable)
- http://xbrl.org/int/dim/arcrole/dimension-domain: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/disclosure/BusinessCombinationsBusinessCombinationSeparatelyRecognizedTransactionsTable)
- http://xbrl.org/int/dim/arcrole/hypercube-dimension: from=us-gaap:EmbeddedDerivativeTable -> to=us-gaap:BalanceSheetLocationAxis (role=http://fasb.org/us-gaap/role/disclosure/DerivativeInstrumentsAndHedgingActivitiesEmbeddedDerivativeTable)
- http://xbrl.org/int/dim/arcrole/dimension-default: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/disclosure/DerivativeInstrumentsAndHedgingActivitiesEmbeddedDerivativeTable)
- http://xbrl.org/int/dim/arcrole/dimension-domain: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/disclosure/DerivativeInstrumentsAndHedgingActivitiesEmbeddedDerivativeTable)
- http://xbrl.org/int/dim/arcrole/hypercube-dimension: from=us-gaap:ForeignCurrencyFairValueHedgeDerivativeTable -> to=us-gaap:BalanceSheetLocationAxis (role=http://fasb.org/us-gaap/role/disclosure/DerivativeInstrumentsAndHedgingActivitiesForeignCurrencyFairValueHedgeDerivativeTable)
- http://xbrl.org/int/dim/arcrole/dimension-default: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/disclosure/DerivativeInstrumentsAndHedgingActivitiesForeignCurrencyFairValueHedgeDerivativeTable)
- http://xbrl.org/int/dim/arcrole/dimension-domain: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/disclosure/DerivativeInstrumentsAndHedgingActivitiesForeignCurrencyFairValueHedgeDerivativeTable)
- http://xbrl.org/int/dim/arcrole/hypercube-dimension: from=us-gaap:HybridInstrumentsTable -> to=us-gaap:BalanceSheetLocationAxis (role=http://fasb.org/us-gaap/role/disclosure/DerivativeInstrumentsAndHedgingActivitiesHybridInstrumentsTable)
- http://xbrl.org/int/dim/arcrole/dimension-default: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/disclosure/DerivativeInstrumentsAndHedgingActivitiesHybridInstrumentsTable)
- http://xbrl.org/int/dim/arcrole/dimension-domain: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/disclosure/DerivativeInstrumentsAndHedgingActivitiesHybridInstrumentsTable)
- http://xbrl.org/int/dim/arcrole/hypercube-dimension: from=us-gaap:PriceRiskDerivativesTable -> to=us-gaap:BalanceSheetLocationAxis (role=http://fasb.org/us-gaap/role/disclosure/DerivativeInstrumentsAndHedgingActivitiesPriceRiskDerivativesTable)
- http://xbrl.org/int/dim/arcrole/dimension-default: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/disclosure/DerivativeInstrumentsAndHedgingActivitiesPriceRiskDerivativesTable)
- http://xbrl.org/int/dim/arcrole/dimension-domain: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/disclosure/DerivativeInstrumentsAndHedgingActivitiesPriceRiskDerivativesTable)
- http://xbrl.org/int/dim/arcrole/hypercube-dimension: from=us-gaap:ScheduleOfCreditDerivativesTable -> to=us-gaap:BalanceSheetLocationAxis (role=http://fasb.org/us-gaap/role/disclosure/DerivativeInstrumentsAndHedgingActivitiesScheduleOfCreditDerivativesTable)
- http://xbrl.org/int/dim/arcrole/dimension-default: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/disclosure/DerivativeInstrumentsAndHedgingActivitiesScheduleOfCreditDerivativesTable)
- http://xbrl.org/int/dim/arcrole/dimension-domain: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/disclosure/DerivativeInstrumentsAndHedgingActivitiesScheduleOfCreditDerivativesTable)
- http://xbrl.org/int/dim/arcrole/hypercube-dimension: from=us-gaap:ScheduleOfDifferencesBetweenReportedAmountAndReportingCurrencyDenominatedAmountTable -> to=us-gaap:BalanceSheetLocationAxis (role=http://fasb.org/us-gaap/role/disclosure/ForeignOperationsAndCurrencyTranslationScheduleOfDifferencesBetweenReportedAmountAndReportingCurrencyDenominatedAmountTable)
- http://xbrl.org/int/dim/arcrole/dimension-default: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/disclosure/ForeignOperationsAndCurrencyTranslationScheduleOfDifferencesBetweenReportedAmountAndReportingCurrencyDenominatedAmountTable)
- http://xbrl.org/int/dim/arcrole/dimension-domain: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/disclosure/ForeignOperationsAndCurrencyTranslationScheduleOfDifferencesBetweenReportedAmountAndReportingCurrencyDenominatedAmountTable)
- http://xbrl.org/int/dim/arcrole/hypercube-dimension: from=us-gaap:RecordedThirdPartyEnvironmentalRecoveriesTable -> to=us-gaap:BalanceSheetLocationAxis (role=http://fasb.org/us-gaap/role/disclosure/EnvironmentalRemediationObligationsRecordedThirdPartyEnvironmentalRecoveriesTable)
- http://xbrl.org/int/dim/arcrole/dimension-default: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/disclosure/EnvironmentalRemediationObligationsRecordedThirdPartyEnvironmentalRecoveriesTable)
- http://xbrl.org/int/dim/arcrole/dimension-domain: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/disclosure/EnvironmentalRemediationObligationsRecordedThirdPartyEnvironmentalRecoveriesTable)
- http://xbrl.org/int/dim/arcrole/hypercube-dimension: from=us-gaap:ProductWarrantyLiabilityTable -> to=us-gaap:BalanceSheetLocationAxis (role=http://fasb.org/us-gaap/role/disclosure/GuaranteesProductWarrantyLiabilityTable)
- http://xbrl.org/int/dim/arcrole/dimension-default: from=us-gaap:BalanceSheetLocationAxis -> to=us-gaap:BalanceSheetLocationDomain (role=http://fasb.org/us-gaap/role/disclosure/GuaranteesProductWarrantyLiabilityTable)

In [21]:
# new_df.to_excel(selected_task_file, index=False)